params:
  periods: 5000  # number of rows of the time series to be generated
  switching_probability: 0.05 #0.05
  min_model_len: 1  # A model should be used at least during this number of iterations
  abrupt_drift_prob: 0.25
  gradual_drift_sharpness: 0.10   # number from 1 to 10 (10 is an instant switch)
  abrupt_drift_sharpness: 0.70
  white_noise_level: 0.05  # weight of white noise (WN) in the generated TS as a %. 0 = no WN. # 100 only produces WN
  w_func: 'sig'  # function to change weights (sig:sigmoid or linear)
  param_search: 'ARMA_GARCH'  # Search of lag values focuses on model: 'ARMA', 'ARMA_GARCH'
  pq_rng: 5  # ARMA lag order range
  d_rng: 1   # [0] # we'll use arma-garch, so not d (= 0) - just for ARIMA
  garch_pq_rng: 5  # GARCH lag order range
  use_transition_map: True  # If True, switches will be pre-defined by the map below
  transition_map: [[300, 2, 3], [550, 20, 2], [2200, 4, 1], [3500, 2, 2], [3800, 60, 3], [4400, 10, 4]]  # iteration of switch (in ASC order), duration of switch as a number of iterations, and model destination at switch

# ASC: un inconveniente que veo a ajustar funciones de este tipo a este tipo de datos es que realmente los modelos
  # nunca van a ajustar bien, al ser datos donde esperamos tasas de prediccion de un 60% solo.
# model 4 -> aic: -9.59773 | order: (0, 0, 1, 1, 1)

input:  # model-related
  path: '.\\data\\'  # C:\\Users\\suare\\MEGA\\PhD\\1 Code and data
  files:  # series for the pre-training of the models (each model will be pre-trained with one), lags and probs
    - [1, 'aapl\\APPLE_[2018-08-01_to_2018-09-11]_5min.csv', [4, 0, 3, 1, 1], 0.25] # aug 2018 only
    - [2, 'btc\\BITCOIN_[2019-07-01_to_2019-07-15]_5min.csv', [4, 0, 5, 1, 5], 0.25]  # first half of july 2019 only
#    - [2, 'efts\\30min-level\\IBEX\\IBEX_[2017-07-01_to_2017-31-12]_market_hours.csv', [5, 0, 5, 5, 5], 0.25]  # nov 2015 only  [(5, 0, 5, 5, 5)]
    - [3, 'efts\\30min-level\\IBEX\\IBEX_[2017-01-01_to_2017-31-12]_market_hours.csv', [-1], 0.25]  # nov 2015 only  [(5, 0, 5, 5, 5)]
#      BEST Model 2 p=1 -> aic: -10.40491 | order: (1, 0, 1, 2, 1)
#      BEST Model 2 p=2 -> aic: -10.39698 | order: (2, 0, 2, 5, 1)
#      BEST Model 2 p=3 -> aic: -10.40038 | order: (3, 0, 1, 1, 1)
#      BEST Model 2 p=4 -> aic: -10.39804 | order: (4, 0, 2, 2, 3)
#      BEST Model 2 p=5 -> aic: -10.40002 | order: (5, 0, 1, 3, 2)
#      BEST Model 2 p=5 -> aic: -10.38356 | order: (5, 0, 5, 5, 5)
    - [4, 'efts\\5min-level\\DOWJONES\\DOWJONES_[2015-08-01_to_2015-08-31]_market_hours.csv', [2, 0, 5, 2, 1], 0.25]  # aug 2015 only
# ----------IBEX_[2017-01-01_to_2017-31-12]_market_hours
#    - [1, 'raw\\quantquote\\one_second_level\\242321_csv\\20151214/spy.csv', [-1], 0.25]
#    - [2, '20170717\\spy.csv', [4, 0, 3, 1, 1], prob]
#    - [3, 'raw\\quantquote\\one_second_level\\242321_csv\\20160914/spy.csv', [-1], 0.25]
#    - [4, 'raw\\quantquote\\one_second_level\\242321_csv\\20170914/spy.csv', [-1], 0.25]
#    - [5, 'raw\\quantquote\\one_second_level\\242321_csv\\20170314/spy.csv', [-1], 0.25]
#    - [6, 'raw\\quantquote\\one_second_level\\242321_csv\\20160314/spy.csv', [-1], 0.25]
#    - [7, 'raw\\quantquote\\one_second_level\\242321_csv\\20151214/spy.csv', [-1], 0.25]
#  cols: ['Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Suspicious']
  sim_col: 'close'
  index_col: 'datetime' # 'Time'
  parsing_mode: 'returns'  # or 'prices'

output:
  path: '.\\output'
  ts_name: 'timeseries_created_'
  cols: [ 'n_row', 'new_switch', 'cur_switch', 'current_model_id', 'new_model_id', 'weights',
          'ts', 'ret_ts', 'ts_n1_pre', 'ts_n2_pre', 'ts_n1_post', 'ts_n2_post']

plot: False  # plot TS?

env:
  r_libs_path: 'C:/Users/suare/OneDrive/Documents/asuare/R/win-library/3.6' # rugarch should be installed there

