params:
  periods: 100  # number of rows of the time series to be generated
  switching_probability: 0.75 #0.05
  min_model_len: 1  # A model should be used at least during this number of iterations
  abrupt_drift_prob: 0.25
  gradual_drift_sharpness: 0.10   # number from 1 to 10 (10 is an instant switch)
  abrupt_drift_sharpness: 0.70
  white_noise_level: 0.05  # weight of white noise (WN) in the generated TS as a %. 0 = no WN. # 100 only produces WN
  w_func: 'sig'  # function to change weights (sig:sigmoid or linear)
  param_search: 'ARMA_GARCH'  # Search of lag values focuses on model: 'ARMA', 'ARMA_GARCH'
  pq_rng: 5  # ARMA lag order range
  d_rng: 1   # [0] # we'll use arma-garch, so not d (= 0) - just for ARIMA
  garch_pq_rng: 5  # GARCH lag order range
  use_transition_map: True  # If True, switches will be pre-defined by the map below
  transition_map: [[10, 2], [30, 7], [50, 4]]  # iteration of switch (in ASC order), and duration of switch as a number of iterations

input:  # model-related
  path: 'C:\\Users\\suare\\MEGA\\PhD\\1 Code and data\\data\\'
  files:  # series for the pre-training of the models (each model will be pre-trained with one)
    - [1, 'raw\\quantquote\\one_second_level\\242321_csv\\20151214/spy.csv', 0.25]
    - [2, 'raw\\quantquote\\one_second_level\\242321_csv\\20170717/spy.csv', 0.25]
    - [3, 'raw\\quantquote\\one_second_level\\242321_csv\\20160914/spy.csv', 0.25]
#    - [4, 'raw\\quantquote\\one_second_level\\242321_csv\\20170914/spy.csv', 0.25]
#    - [5, 'raw\\quantquote\\one_second_level\\242321_csv\\20170314/spy.csv', 0.25]
#    - [6, 'raw\\quantquote\\one_second_level\\242321_csv\\20160314/spy.csv', 0.25]
#    - [7, 'raw\\quantquote\\one_second_level\\242321_csv\\20151214/spy.csv', 0.25]
  cols: ['Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Suspicious']
  sim_col: 'Close'
  index_col: 'Time'
  parsing_mode: 'returns'  # or 'prices'

output:
  path: '.\\output'
  ts_name: 'timeseries_created_1.csv'
  cols: [ 'n_row', 'new_switch', 'cur_switch', 'current_model_id', 'new_model_id', 'weights',
          'ts', 'ret_ts', 'ts_n1_pre', 'ts_n2_pre', 'ts_n1_post', 'ts_n2_post']

plot: False  # plot TS?

env:
  r_libs_path: 'C:/Users/suare/OneDrive/Documents/asuare/R/win-library/3.6' # rugarch should be installed there

