params:
  periods: 5000  # number of rows of the time series to be generated
  switching_probability: 0.05 #0.05
  min_model_len: 1  # A model should be used at least during this number of iterations
  abrupt_drift_prob: 0.25
  gradual_drift_sharpness: 0.10   # number from 1 to 10 (10 is an instant switch)
  abrupt_drift_sharpness: 0.70
  white_noise_level: 0.05  # weight of white noise (WN) in the generated TS as a %. 0 = no WN. # 100 only produces WN
  w_func: 'sig'  # function to change weights (sig:sigmoid or linear)
  param_search: 'ARMA_GARCH'  # Search of lag values focuses on model: 'ARMA', 'ARMA_GARCH'
  pq_rng: 5  # ARMA lag order range
  d_rng: 1   # [0] # we'll use arma-garch, so not d (= 0) - just for ARIMA
  garch_pq_rng: 5  # GARCH lag order range
  use_transition_map: True  # If True, switches will be pre-defined by the map below
  transition_map: [[300, 2], [550, 20], [2200, 4], [3500,2], [3800,60], [4400,10]]  # iteration of switch (in ASC order), and duration of switch as a number of iterations

# ASC: un inconveniente que veo a ajustar funciones de este tipo a este tipo de datos es que realmente los modelos
  # nunca van a ajustar bien, al ser datos donde esperamos tasas de prediccion de un 60% solo.
# model 4 -> aic: -9.59773 | order: (0, 0, 1, 1, 1)

input:  # model-related
  path: '.\\data\\'  # C:\\Users\\suare\\MEGA\\PhD\\1 Code and data
  files:  # series for the pre-training of the models (each model will be pre-trained with one), lags and probs
    - [1, 'aapl\\APPLE_[2018-08-01_to_2018-09-11]_5min.csv', [4, 0, 3, 1, 1], prob] # aug 2018 only # TODO add best o,p,q,.. config
    - [2, 'btc\\BITCOIN_[2019-07-01_to_2019-08-01]_5min.csv', [5, 0, 5, 1, 5], prob]  # july 2019 only
    - [3, 'efts\\5min-level\\IBEX\\IBEX_[2015-11-01_to_2015-11-30].csv', [1, 0, 1, 1, 5], prob]  # nov 2015 only
    - [4, 'efts\\5min-level\\DOWJONES\\DOWJONES_[2015-08-01_to_2015-08-31].csv', [1, 0, 1, 1, 1], prob]  # aug 2015 only  [1, 0, 1, 1, 1]
#    - [1, 'raw\\quantquote\\one_second_level\\242321_csv\\20151214/spy.csv', 0.25]
#    - [2, 'raw\\quantquote\\one_second_level\\242321_csv\\20170717/spy.csv', 0.25]
#    - [3, 'raw\\quantquote\\one_second_level\\242321_csv\\20160914/spy.csv', 0.25]
#    - [4, 'raw\\quantquote\\one_second_level\\242321_csv\\20170914/spy.csv', 0.25]
#    - [5, 'raw\\quantquote\\one_second_level\\242321_csv\\20170314/spy.csv', 0.25]
#    - [6, 'raw\\quantquote\\one_second_level\\242321_csv\\20160314/spy.csv', 0.25]
#    - [7, 'raw\\quantquote\\one_second_level\\242321_csv\\20151214/spy.csv', 0.25]
#  cols: ['Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Suspicious']
  sim_col: 'close'
  index_col: 'datetime' # 'Time'
  parsing_mode: 'returns'  # or 'prices'

output:
  path: '.\\output'
  ts_name: 'timeseries_created_1.csv'
  cols: [ 'n_row', 'new_switch', 'cur_switch', 'current_model_id', 'new_model_id', 'weights',
          'ts', 'ret_ts', 'ts_n1_pre', 'ts_n2_pre', 'ts_n1_post', 'ts_n2_post']

plot: False  # plot TS?

env:
  r_libs_path: 'C:/Users/suare/OneDrive/Documents/asuare/R/win-library/3.6' # rugarch should be installed there

